apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: little-node
  name: little-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: little-node
  template:
    metadata:
      labels:
        app: little-node
    spec:
      containers:
        - image: gcr.io/$PROJECT_ID/sinmetal/little_spanner/feature/id/22:60605d1308ff8d193b05aa14e3521319e72414af
          name: little-node
          envFrom:
            - configMapRef:
                name: little-config